[versions]
agp = "8.8.0"
cameraCore = "1.4.0"
comGoogleApisGoogleApiServicesDrive = "v3-rev197-1.25.0"
googleApiClient = "2.7.0"
googleApiClientAndroid = "2.0.0"
googleApiClientAndroidVersion = "1.33.2"
googleApiClientVersion = "1.34.0"
googleApiServicesDrive = "v3-rev136-1.25.0"
googleApiServicesDriveactivity = "v2-rev20210319-1.32.1"
googleApiServicesDriveVersion = "v3-rev305-1.25.0"
googleAuthLibraryOauth2Http = "1.15.0"
googleGoogleApiClient = "1.25.0"
googleGoogleApiClientAndroid = "1.34.0"
googleGoogleApiServicesDrive = "v3-rev305-1.34.0"
googleGoogleApiServicesDriveVersion = "v3-rev20220815-2.0.0"
googleHttpClientAndroid = "1.42.2"
googleHttpClientJackson2 = "1.42.3"
googlePlayServicesAuth = "20.5.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
okhttp = "3.10.0"
opencvAndroid = "4.5.5"
cameraLifecycle = "1.4.0"
playServicesAuth = "21.2.0"

[libraries]
camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraCore" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraCore" }
google-api-client = { module = "com.google.api-client:google-api-client", version.ref = "googleApiClient" }
google-api-client-android = { module = "com.google.api-client:google-api-client-android", version.ref = "googleApiClientAndroid" }
google-api-client-android-v1332 = { module = "com.google.api-client:google-api-client-android", version.ref = "googleApiClientAndroidVersion" }
google-api-client-android-v1340 = { module = "com.google.api-client:google-api-client-android", version.ref = "googleGoogleApiClientAndroid" }
google-api-client-v1250 = { module = "com.google.api-client:google-api-client", version.ref = "googleGoogleApiClient" }
google-api-client-v1340 = { module = "com.google.api-client:google-api-client", version.ref = "googleApiClientVersion" }
google-api-services-drive = { module = "com.google.apis:google-api-services-drive", version.ref = "googleApiServicesDrive" }
google-api-services-drive-vv3rev1971250 = { module = "com.google.apis:google-api-services-drive", version.ref = "comGoogleApisGoogleApiServicesDrive" }
google-api-services-drive-vv3rev20220815200 = { module = "com.google.apis:google-api-services-drive", version.ref = "googleGoogleApiServicesDriveVersion" }
google-api-services-drive-vv3rev3051250 = { module = "com.google.apis:google-api-services-drive", version.ref = "googleApiServicesDriveVersion" }
google-api-services-drive-vv3rev3051340 = { module = "com.google.apis:google-api-services-drive", version.ref = "googleGoogleApiServicesDrive" }
google-api-services-driveactivity = { module = "com.google.apis:google-api-services-driveactivity", version.ref = "googleApiServicesDriveactivity" }
google-auth-library-oauth2-http = { module = "com.google.auth:google-auth-library-oauth2-http", version.ref = "googleAuthLibraryOauth2Http" }
google-http-client-android = { module = "com.google.http-client:google-http-client-android", version.ref = "googleHttpClientAndroid" }
google-http-client-jackson2 = { module = "com.google.http-client:google-http-client-jackson2", version.ref = "googleHttpClientJackson2" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
opencv-android = { module = "org.opencv:opencv-android", version.ref = "opencvAndroid" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraLifecycle" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
play-services-auth-v2050 = { module = "com.google.android.gms:play-services-auth", version.ref = "googlePlayServicesAuth" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

